ALTER TABLE leads
  ADD COLUMN creator_id INT DEFAULT NULL,
  ADD COLUMN creator_name VARCHAR(100) DEFAULT NULL,
  ADD COLUMN creator_email VARCHAR(150) DEFAULT NULL,
  ADD COLUMN campaign_name VARCHAR(255) DEFAULT NULL;
